/*******************************************************************************
 * Copyright (c) 2006-2013
 * Software Technology Group, Dresden University of Technology
 * DevBoost GmbH, Berlin, Amtsgericht Charlottenburg, HRB 140026
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *   Software Technology Group - TU Dresden, Germany;
 *   DevBoost GmbH - Berlin, Germany
 *      - initial API and implementation
 ******************************************************************************/
package org.emftext.sdk.codegen.resource.ui;

import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.io.PushbackReader;
import java.io.Reader;
import java.io.StringReader;
import java.io.StringWriter;
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Proxy;
import java.net.URL;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.Enumeration;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.Set;
import java.util.Stack;
import java.util.Timer;
import java.util.TimerTask;
import java.util.regex.Matcher;

import javax.swing.event.DocumentListener;

import org.antlr.runtime3_4_0.ANTLRInputStream;
import org.antlr.runtime3_4_0.ANTLRStringStream;
import org.antlr.runtime3_4_0.BitSet;
import org.antlr.runtime3_4_0.CommonToken;
import org.antlr.runtime3_4_0.CommonTokenStream;
import org.antlr.runtime3_4_0.EarlyExitException;
import org.antlr.runtime3_4_0.FailedPredicateException;
import org.antlr.runtime3_4_0.IntStream;
import org.antlr.runtime3_4_0.Lexer;
import org.antlr.runtime3_4_0.MismatchedNotSetException;
import org.antlr.runtime3_4_0.MismatchedRangeException;
import org.antlr.runtime3_4_0.MismatchedSetException;
import org.antlr.runtime3_4_0.MismatchedTokenException;
import org.antlr.runtime3_4_0.MismatchedTreeNodeException;
import org.antlr.runtime3_4_0.NoViableAltException;
import org.antlr.runtime3_4_0.RecognitionException;
import org.eclipse.core.resources.ICommand;
import org.eclipse.core.resources.IContainer;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IMarker;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.IProjectDescription;
import org.eclipse.core.resources.IProjectNature;
import org.eclipse.core.resources.IResource;
import org.eclipse.core.resources.IResourceChangeEvent;
import org.eclipse.core.resources.IResourceChangeListener;
import org.eclipse.core.resources.IResourceDelta;
import org.eclipse.core.resources.IResourceDeltaVisitor;
import org.eclipse.core.resources.IWorkspace;
import org.eclipse.core.resources.IWorkspaceRoot;
import org.eclipse.core.resources.IncrementalProjectBuilder;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.Assert;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.IConfigurationElement;
import org.eclipse.core.runtime.IExtensionRegistry;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.core.runtime.IStatus;
import org.eclipse.core.runtime.ListenerList;
import org.eclipse.core.runtime.Path;
import org.eclipse.core.runtime.Platform;
import org.eclipse.core.runtime.SafeRunner;
import org.eclipse.core.runtime.Status;
import org.eclipse.core.runtime.SubProgressMonitor;
import org.eclipse.core.runtime.preferences.AbstractPreferenceInitializer;
import org.eclipse.debug.core.DebugPlugin;
import org.eclipse.debug.core.ILaunch;
import org.eclipse.debug.core.ILaunchConfiguration;
import org.eclipse.debug.core.ILaunchConfigurationType;
import org.eclipse.debug.core.ILaunchConfigurationWorkingCopy;
import org.eclipse.debug.core.model.ILineBreakpoint;
import org.eclipse.emf.codegen.ecore.genmodel.GenClass;
import org.eclipse.emf.codegen.ecore.genmodel.GenFeature;
import org.eclipse.emf.codegen.ecore.genmodel.GenPackage;
import org.eclipse.emf.codegen.ecore.templates.editor.Editor;
import org.eclipse.emf.common.command.BasicCommandStack;
import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.common.notify.impl.AdapterImpl;
import org.eclipse.emf.common.util.BasicEList;
import org.eclipse.emf.common.util.BasicEMap;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;
import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EClassifier;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EEnumLiteral;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EOperation;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.emf.ecore.EcoreFactory;
import org.eclipse.emf.ecore.InternalEObject;
import org.eclipse.emf.ecore.impl.EObjectImpl;
import org.eclipse.emf.ecore.provider.EcoreItemProviderAdapterFactory;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.Resource.Diagnostic;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.emf.ecore.resource.URIConverter;
import org.eclipse.emf.ecore.resource.impl.ResourceImpl;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.eclipse.emf.ecore.util.BasicInternalEList;
import org.eclipse.emf.ecore.util.EObjectWithInverseResolvingEList;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.util.InternalEList;
import org.eclipse.emf.edit.domain.AdapterFactoryEditingDomain;
import org.eclipse.emf.edit.domain.EditingDomain;
import org.eclipse.emf.edit.domain.IEditingDomainProvider;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.ReflectiveItemProviderAdapterFactory;
import org.eclipse.emf.edit.provider.resource.ResourceItemProviderAdapterFactory;
import org.eclipse.emf.validation.model.ConstraintStatus;
import org.eclipse.emf.validation.model.EvaluationMode;
import org.eclipse.emf.validation.service.IBatchValidator;
import org.eclipse.emf.validation.service.ModelValidationService;
import org.emftext.sdk.codegen.resource.generators.IClassNameConstants;
import org.osgi.framework.Bundle;
import org.osgi.framework.BundleContext;

/**
 * Constants for class names used in the generated code.
 */
public interface IUIClassNameConstants extends IClassNameConstants {
	
	public static String ABSTRACT_INFORMATION_CONTROL = "org.eclipse.jface.text.AbstractInformationControl";
	public static String ABSTRACT_LAUNCH_CONFIGURATION_TAB = "org.eclipse.debug.ui.AbstractLaunchConfigurationTab";
	public static String ABSTRACT_LAUNCH_CONFIGURATION_TAB_GROUP = "org.eclipse.debug.ui.AbstractLaunchConfigurationTabGroup";
	public static String ABSTRACT_MARKER_ANNOTATION_MODEL = "org.eclipse.ui.texteditor.AbstractMarkerAnnotationModel";
	public static String ABSTRACT_PREFERENCE_INITIALIZER = AbstractPreferenceInitializer.class.getName();
	public static String ABSTRACT_REUSABLE_INFORMATION_CONTROL_CREATOR = "org.eclipse.jface.text.AbstractReusableInformationControlCreator";
	public static String ABSTRACT_UI_PLUGIN = "org.eclipse.ui.plugin.AbstractUIPlugin";
	public static String ACTION = "org.eclipse.jface.action.Action";
	public static String ADAPTER = Adapter.class.getName();
	public static String ADAPTER_FACTORY_CONTENT_PROVIDER = "org.eclipse.emf.edit.ui.provider.AdapterFactoryContentProvider";
	public static String ADAPTER_FACTORY_EDITING_DOMAIN = AdapterFactoryEditingDomain.class.getName();
	public static String ADAPTER_FACTORY_LABEL_PROVIDER = "org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider";
	public static String ADAPTER_IMPL = AdapterImpl.class.getName();
	public static String ANNOTATION = "org.eclipse.jface.text.source.Annotation";
	public static String ANTLR_INPUT_STREAM = ANTLRInputStream.class.getName();
	public static String ANTLR_PARSER = org.antlr.runtime3_4_0.Parser.class.getName();
	public static String ANTLR_STRING_STREAM = ANTLRStringStream.class.getName();
	public static String ARRAYS = java.util.Arrays.class.getName();
	public static String ARRAY_LIST = ArrayList.class.getName();
	public static String ASSERT = Assert.class.getName();
	public static String BAD_LOCATION_EXCEPTION = "org.eclipse.jface.text.BadLocationException";
	public static String BAD_POSITION_CATEGORY_EXCEPTION = "org.eclipse.jface.text.BadPositionCategoryException";
	public static String BASIC_COMMAND_STACK = BasicCommandStack.class.getName();
	public static String BASIC_E_LIST = BasicEList.class.getName();
	public static String BASIC_E_MAP = BasicEMap.class.getName();
	public static String BASIC_INTERNAL_E_LIST = BasicInternalEList.class.getName();
	public static String BIT_SET = BitSet.class.getName();
	public static String BROWSER = "org.eclipse.swt.browser.Browser";
	public static String BUFFERED_OUTPUT_STREAM = BufferedOutputStream.class.getName();
	public static String BUFFERED_READER = BufferedReader.class.getName();
	public static String BUNDLE = Bundle.class.getName();
	public static String BUNDLE_CONTEXT = BundleContext.class.getName();
	public static String BUSY_INDICATOR = "org.eclipse.swt.custom.BusyIndicator";
	public static String BUTTON = "org.eclipse.swt.widgets.Button";
	public static String BYTE_ARRAY_INPUT_STREAM = ByteArrayInputStream.class.getName();
	public static String BYTE_ARRAY_OUTPUT_STREAM = ByteArrayOutputStream.class.getName();
	public static String CELL_EDITOR = "org.eclipse.jface.viewers.CellEditor";
	public static String COLLECTION = Collection.class.getName();
	public static String COLLECTIONS = Collections.class.getName();
	public static String COLOR = "org.eclipse.swt.graphics.Color";
	public static String COLOR_SELECTOR = "org.eclipse.jface.preference.ColorSelector";
	public static String COMBO = "org.eclipse.swt.widgets.Combo";
	public static String COMMON_TOKEN = CommonToken.class.getName();
	public static String COMMON_TOKEN_STREAM = CommonTokenStream.class.getName();
	public static String COMPARABLE = Comparable.class.getName();
	public static String COMPARATOR = Comparator.class.getName();
	public static String COMPLETION_PROPOSAL = "org.eclipse.jface.text.contentassist.CompletionProposal";
	public static String COMPOSED_ADAPTER_FACTORY = ComposedAdapterFactory.class.getName();
	public static String COMPOSITE = "org.eclipse.swt.widgets.Composite";
	public static String CONSTRAINT_STATUS = ConstraintStatus.class.getName();
	public static String CONTAINER_SELECTION_DIALOG = "org.eclipse.ui.dialogs.ContainerSelectionDialog";
	public static String CONTENT_ASSISTANT = "org.eclipse.jface.text.contentassist.ContentAssistant";
	public static String CONTENT_ASSIST_ACTION = "org.eclipse.ui.texteditor.ContentAssistAction";
	public static String CONTEXT_INFORMATION = "org.eclipse.jface.text.contentassist.ContextInformation";
	public static String CONTROL = "org.eclipse.swt.widgets.Control";
	public static String CORE_EXCEPTION = CoreException.class.getName();
	public static String DEBUG_PLUGIN = DebugPlugin.class.getName();
	public static String DEBUG_UI_TOOLS = "org.eclipse.debug.ui.DebugUITools";
	public static String DEFAULT_ANNOTATION_HOVER = "org.eclipse.jface.text.source.DefaultAnnotationHover";
	public static String DEFAULT_DAMAGER_REPAIRER = "org.eclipse.jface.text.rules.DefaultDamagerRepairer";
	public static String DEFAULT_INDENT_LINE_AUTO_EDIT_STRATEGY = "org.eclipse.jface.text.DefaultIndentLineAutoEditStrategy";
	public static String DEFAULT_INFORMATION_CONTROL = "org.eclipse.jface.text.DefaultInformationControl";
	public static String DIAGNOSTIC = org.eclipse.emf.common.util.Diagnostic.class.getName();
	public static String DIAGNOSTICIAN = org.eclipse.emf.ecore.util.Diagnostician.class.getName();
	public static String DIALOG = "org.eclipse.swt.widgets.Dialog";
	public static String DISPLAY = "org.eclipse.swt.widgets.Display";
	public static String DOCUMENT = "org.eclipse.jface.text.Document";
	public static String DOCUMENT_COMMAND = "org.eclipse.jface.text.DocumentCommand";
	public static String DOCUMENT_EVENT = "org.eclipse.jface.text.DocumentEvent";
	public static String DOCUMENT_LISTENER = DocumentListener.class.getName();
	public static String EARLY_EXIT_EXCEPTION = EarlyExitException.class.getName();
	public static String ECORE_FACTORY = EcoreFactory.class.getName();
	public static String ECORE_ITEM_PROVIDER_ADAPTER_FACTORY = EcoreItemProviderAdapterFactory.class.getName();
	public static String ECORE_UTIL = EcoreUtil.class.getName();
	public static String EDITING_DOMAIN = EditingDomain.class.getName();
	public static String EDITOR = Editor.class.getName();
	public static String EDITORS_UI = "org.eclipse.ui.editors.text.EditorsUI";
	public static String ELEMENT_BASED_TEXT_DIAGNOSTIC = "org.emftext.sdk.concretesyntax.resource.cs.mopp.CsResource.ElementBasedTextDiagnostic";
	public static String ELEMENT_TREE_SELECTION_DIALOG = "org.eclipse.ui.dialogs.ElementTreeSelectionDialog";
	public static String ENUMERATION = Enumeration.class.getName();
	public static String EVALUATION_MODE = EvaluationMode.class.getName();
	public static String EVENT = "org.eclipse.swt.widgets.Event";
	public static String E_ATTRIBUTE = EAttribute.class.getName();
	public static String E_CLASS = EClass.class.getName();
	public static String E_CLASSIFIER = EClassifier.class.getName();
	public static String E_DATA_TYPE = EDataType.class.getName();
	public static String E_ENUM = EEnum.class.getName();
	public static String E_ENUM_LITERAL = EEnumLiteral.class.getName();
	public static String E_LIST = EList.class.getName();
	public static String E_MAP = EMap.class.getName();
	public static String E_OBJECT = EObject.class.getName();
	public static String E_OBJECT_IMPL = EObjectImpl.class.getName();
	public static String E_OPERATION = EOperation.class.getName();
	public static String E_PACKAGE = EPackage.class.getName();
	public static String E_REFERENCE = EReference.class.getName();
	public static String E_STRUCTURAL_FEATURE = EStructuralFeature.class.getName();
	public static String FAILED_PREDICATE_EXCEPTION = FailedPredicateException.class.getName();
	public static String FILE = File.class.getName();
	public static String FILE_DIALOG = "org.eclipse.swt.widgets.FileDialog";
	public static String FILE_DOCUMENT_PROVIDER = "org.eclipse.ui.editors.text.FileDocumentProvider";
	public static String FILE_EDITOR_INPUT = "org.eclipse.ui.part.FileEditorInput";
	public static String FILE_INPUT_STREAM = FileInputStream.class.getName();
	public static String FILE_OUTPUT_STREAM = FileOutputStream.class.getName();
	public static String FONT = "org.eclipse.swt.graphics.Font";
	public static String FONT_DATA = "org.eclipse.swt.graphics.FontData";
	public static String FONT_METRICS = "org.eclipse.swt.graphics.FontMetrics";
	public static String GC = "org.eclipse.swt.graphics.GC";
	public static String GEN_CLASS = GenClass.class.getName();
	public static String GEN_FEATURE = GenFeature.class.getName();
	public static String GEN_PACKAGE = GenPackage.class.getName();
	public static String GRID_DATA = "org.eclipse.swt.layout.GridData";
	public static String GRID_LAYOUT = "org.eclipse.swt.layout.GridLayout";
	public static String GROUP = "org.eclipse.swt.widgets.Group";
	public static String GROUP_MARKER = "org.eclipse.jface.action.GroupMarker";
	public static String I_ELEMENT_COMPARER = "org.eclipse.jface.viewers.IElementComparer";
	public static String IDE = "org.eclipse.ui.ide.IDE";
	public static String ILLEGAL_ARGUMENT_EXCEPTION = IllegalArgumentException.class.getName();
	public static String IMAGE = "org.eclipse.swt.graphics.Image";
	public static String IMAGE_DATA = "org.eclipse.swt.graphics.ImageData";
	public static String IMAGE_DESCRIPTOR = "org.eclipse.jface.resource.ImageDescriptor";
	public static String IMAGE_LOADER = "org.eclipse.swt.graphics.ImageLoader";
	public static String INCREMENTAL_PROJECT_BUILDER = IncrementalProjectBuilder.class.getName();
	public static String INPUT_STREAM = InputStream.class.getName();
	public static String INPUT_STREAM_READER = InputStreamReader.class.getName();
	public static String INTEGER = Integer.class.getName();
	public static String INTERNAL_E_LIST = InternalEList.class.getName();
	public static String INTERNAL_E_OBJECT = InternalEObject.class.getName();
	public static String INT_STREAM = IntStream.class.getName();
	public static String INVOCATION_HANDLER = InvocationHandler.class.getName();
	public static String INVOCATION_TARGET_EXCEPTION = InvocationTargetException.class.getName();
	public static String IO_EXCEPTION = IOException.class.getName();
	public static String ITERATOR = Iterator.class.getName();
	public static String I_ACTION = "org.eclipse.jface.action.IAction";
	public static String I_ACTION_BARS = "org.eclipse.ui.IActionBars";
	public static String I_ADAPTABLE = org.eclipse.core.runtime.IAdaptable.class.getName();
	public static String I_ANNOTATION_ACCESS_EXTENSION = "org.eclipse.jface.text.source.IAnnotationAccessExtension";
	public static String I_ANNOTATION_HOVER = "org.eclipse.jface.text.source.IAnnotationHover";
	public static String I_ANNOTATION_MODEL = "org.eclipse.jface.text.source.IAnnotationModel";
	public static String I_ANNOTATION_MODEL_FACTORY = "org.eclipse.core.filebuffers.IAnnotationModelFactory";
	public static String I_AUTO_EDIT_STRATEGY = "org.eclipse.jface.text.IAutoEditStrategy";
	public static String I_BATCH_VALIDATOR = IBatchValidator.class.getName();
	public static String I_CHILDREN_COUNT_UPDATE = "org.eclipse.debug.internal.ui.viewers.model.provisional.IChildrenCountUpdate";
	public static String I_CHILDREN_UPDATE = "org.eclipse.debug.internal.ui.viewers.model.provisional.IChildrenUpdate";
	public static String I_COMMAND = ICommand.class.getName();
	public static String I_COMPLETION_PROPOSAL = "org.eclipse.jface.text.contentassist.ICompletionProposal";
	public static String I_CONFIGURATION_ELEMENT = IConfigurationElement.class.getName();
	public static String I_CONTAINER = IContainer.class.getName();
	public static String I_CONTENT_ASSISTANT = "org.eclipse.jface.text.contentassist.IContentAssistant";
	public static String I_CONTENT_ASSIST_PROCESSOR = "org.eclipse.jface.text.contentassist.IContentAssistProcessor";
	public static String I_CONTENT_OUTLINE_PAGE = "org.eclipse.ui.views.contentoutline.IContentOutlinePage";
	public static String I_CONTEXT_INFORMATION = "org.eclipse.jface.text.contentassist.IContextInformation";
	public static String I_CONTEXT_INFORMATION_VALIDATOR = "org.eclipse.jface.text.contentassist.IContextInformationValidator";
	public static String I_DEBUG_MODEL_PRESENTATION = "org.eclipse.debug.ui.IDebugModelPresentation";
	public static String I_DELAYED_INPUT_CHANGE_PROVIDER = "org.eclipse.jface.text.IDelayedInputChangeProvider";
	public static String I_DIALOG_CONSTANTS = "org.eclipse.jface.dialogs.IDialogConstants";
	public static String I_DOCUMENT = "org.eclipse.jface.text.IDocument";
	public static String I_DOCUMENT_LISTENER = "org.eclipse.jface.text.IDocumentListener";
	public static String I_EDITING_DOMAIN_PROVIDER = IEditingDomainProvider.class.getName();
	public static String I_EDITOR_DESCRIPTOR = "org.eclipse.ui.IEditorDescriptor";
	public static String I_EDITOR_INPUT = "org.eclipse.ui.IEditorInput";
	public static String I_EDITOR_PART = "org.eclipse.ui.IEditorPart";
	public static String I_ELEMENT_CONTENT_PROVIDER = "org.eclipse.debug.internal.ui.viewers.model.provisional.IElementContentProvider";
	public static String I_ELEMENT_LABEL_PROVIDER = "org.eclipse.debug.internal.ui.viewers.model.provisional.IElementLabelProvider";
	public static String I_EXTENSION_REGISTRY = IExtensionRegistry.class.getName();
	public static String I_FILE = IFile.class.getName();
	public static String I_FILE_EDITOR_INPUT = "org.eclipse.ui.IFileEditorInput";
	public static String I_HAS_CHILDREN_UPDATE = "org.eclipse.debug.internal.ui.viewers.model.provisional.IHasChildrenUpdate";
	public static String I_HYPERLINK = "org.eclipse.jface.text.hyperlink.IHyperlink";
	public static String I_HYPERLINK_DETECTOR = "org.eclipse.jface.text.hyperlink.IHyperlinkDetector";
	public static String I_INFORMATION_CONTROL = "org.eclipse.jface.text.IInformationControl";
	public static String I_INFORMATION_CONTROL_CREATOR = "org.eclipse.jface.text.IInformationControlCreator";
	public static String I_INFORMATION_CONTROL_EXTENSION2 = "org.eclipse.jface.text.IInformationControlExtension2";
	public static String I_INFORMATION_CONTROL_EXTENSION4 = "org.eclipse.jface.text.IInformationControlExtension4";
	public static String I_INFORMATION_PRESENTER = "org.eclipse.jface.text.DefaultInformationControl.IInformationPresenter";
	public static String I_INPUT_CHANGED_LISTENER = "org.eclipse.jface.text.IInputChangedListener";
	public static String I_ITEM_LABEL_PROVIDER = IItemLabelProvider.class.getName();
	public static String I_ITEM_PROPERTY_DESCRIPTOR = IItemPropertyDescriptor.class.getName();
	public static String I_ITEM_PROPERTY_SOURCE = IItemPropertySource.class.getName();
	public static String I_LABEL_PROVIDER_LISTENER = "org.eclipse.jface.viewers.ILabelProviderListener";
	public static String I_LABEL_UPDATE = "org.eclipse.debug.internal.ui.viewers.model.provisional.ILabelUpdate";
	public static String I_LAUNCH = ILaunch.class.getName();
	public static String I_LAUNCH_CONFIGURATION = ILaunchConfiguration.class.getName();
	public static String I_LAUNCH_CONFIGURATION_DIALOG = "org.eclipse.debug.ui.ILaunchConfigurationDialog";
	public static String I_LAUNCH_CONFIGURATION_TAB = "org.eclipse.debug.ui.ILaunchConfigurationTab";
	public static String I_LAUNCH_CONFIGURATION_TYPE = ILaunchConfigurationType.class.getName();
	public static String I_LAUNCH_CONFIGURATION_WORKING_COPY = ILaunchConfigurationWorkingCopy.class.getName();
	public static String I_LAUNCH_SHORTCUT2 = "org.eclipse.debug.ui.ILaunchShortcut2";
	public static String I_LINE_BREAKPOINT = ILineBreakpoint.class.getName();
	public static String I_MARKER = IMarker.class.getName();
	public static String I_MARKER_RESOLUTION = "org.eclipse.ui.IMarkerResolution";
	public static String I_MARKER_RESOLUTION2 = "org.eclipse.ui.IMarkerResolution2";
	public static String I_MARKER_RESOLUTION_GENERATOR = "org.eclipse.ui.IMarkerResolutionGenerator";
	public static String I_MEMENTO = "org.eclipse.ui.IMemento";
	public static String I_MENU_LISTENER = "org.eclipse.jface.action.IMenuListener";
	public static String I_MENU_MANAGER = "org.eclipse.jface.action.IMenuManager";
	public static String I_NEW_WIZARD = "org.eclipse.ui.INewWizard";
	public static String I_PAGE_SITE = "org.eclipse.ui.part.IPageSite";
	public static String I_PART_LISTENER2 = "org.eclipse.ui.IPartListener2";
	public static String I_PATH = IPath.class.getName();
	public static String I_PREFERENCE_STORE = "org.eclipse.jface.preference.IPreferenceStore";
	public static String I_PRESENTATION_RECONCILER = "org.eclipse.jface.text.presentation.IPresentationReconciler";
	public static String I_PROGRESS_MONITOR = IProgressMonitor.class.getName();
	public static String I_PROJECT = IProject.class.getName();
	public static String I_PROJECT_DESCRIPTION = IProjectDescription.class.getName();
	public static String I_PROJECT_NATURE = IProjectNature.class.getName();
	public static String I_PROPERTY_DESCRIPTOR = "org.eclipse.ui.views.properties.IPropertyDescriptor";
	public static String I_PROPERTY_SHEET_PAGE = "org.eclipse.ui.views.properties.IPropertySheetPage";
	public static String I_PROPERTY_SOURCE = "org.eclipse.ui.views.properties.IPropertySource";
	public static String I_QUICK_ASSIST_ASSISTANT = "org.eclipse.jface.text.quickassist.IQuickAssistAssistant";
	public static String I_QUICK_ASSIST_INVOCATION_CONTEXT = "org.eclipse.jface.text.quickassist.IQuickAssistInvocationContext";
	public static String I_QUICK_ASSIST_PROCESSOR = "org.eclipse.jface.text.quickassist.IQuickAssistProcessor";
	public static String I_QUICK_FIXABLE_ANNOTATION = "org.eclipse.jface.text.quickassist.IQuickFixableAnnotation";
	public static String I_REGION = "org.eclipse.jface.text.IRegion";
	public static String I_RESOURCE = IResource.class.getName();
	public static String I_RESOURCE_CHANGE_EVENT = IResourceChangeEvent.class.getName();
	public static String I_RESOURCE_CHANGE_LISTENER = IResourceChangeListener.class.getName();
	public static String I_RESOURCE_DELTA = IResourceDelta.class.getName();
	public static String I_RESOURCE_DELTA_VISITOR = IResourceDeltaVisitor.class.getName();
	public static String I_RUNNABLE_WITH_PROGRESS = "org.eclipse.jface.operation.IRunnableWithProgress";
	public static String I_SELECTION = "org.eclipse.jface.viewers.ISelection";
	public static String I_SELECTION_CHANGED_LISTENER = "org.eclipse.jface.viewers.ISelectionChangedListener";
	public static String I_SELECTION_PROVIDER = "org.eclipse.jface.viewers.ISelectionProvider";
	public static String I_SELECTION_STATUS_VALIDATOR = "org.eclipse.ui.dialogs.ISelectionStatusValidator";
	public static String I_SHARED_IMAGES = "org.eclipse.ui.ISharedImages";
	public static String I_SOURCE_VIEWER = "org.eclipse.jface.text.source.ISourceViewer";
	public static String I_STATUS = IStatus.class.getName();
	public static String I_STRUCTURED_SELECTION = "org.eclipse.jface.viewers.IStructuredSelection";
	public static String I_TEXT_EDITOR = "org.eclipse.ui.texteditor.ITextEditor";
	public static String I_TEXT_EDITOR_ACTION_CONSTANTS = "org.eclipse.ui.texteditor.ITextEditorActionConstants";
	public static String I_TEXT_EDITOR_ACTION_DEFINITION_IDS = "org.eclipse.ui.texteditor.ITextEditorActionDefinitionIds";
	public static String I_TEXT_HOVER = "org.eclipse.jface.text.ITextHover";
	public static String I_TEXT_HOVER_EXTENSION = "org.eclipse.jface.text.ITextHoverExtension";
	public static String I_TEXT_HOVER_EXTENSION2 = "org.eclipse.jface.text.ITextHoverExtension2";
	public static String I_TEXT_OPERATION_TARGET = "org.eclipse.jface.text.ITextOperationTarget";
	public static String I_TEXT_PRESENTATION_LISTENER = "org.eclipse.jface.text.ITextPresentationListener";
	public static String I_TEXT_SELECTION = "org.eclipse.jface.text.ITextSelection";
	public static String I_TEXT_VIEWER = "org.eclipse.jface.text.ITextViewer";
	public static String I_TOGGLE_BREAKPOINTS_TARGET = "org.eclipse.debug.ui.actions.IToggleBreakpointsTarget";
	public static String I_TOOL_BAR_MANAGER = "org.eclipse.jface.action.IToolBarManager";
	public static String I_TOKEN = "org.eclipse.jface.text.rules.IToken";
	public static String I_TOKEN_SCANNER = "org.eclipse.jface.text.rules.ITokenScanner";
	public static String I_TREE_CONTENT_PROVIDER = "org.eclipse.jface.viewers.ITreeContentProvider";
	public static String I_VALUE_DETAIL_LISTENER = "org.eclipse.debug.ui.IValueDetailListener";
	public static String I_VERTICAL_RULER = "org.eclipse.jface.text.source.IVerticalRuler";
	public static String I_VIEWER_PROVIDER = "org.eclipse.emf.common.ui.viewer.IViewerProvider";
	public static String I_WIZARD = "org.eclipse.jface.wizard.IWizard";
	public static String I_WIZARD_CATEGORY = "org.eclipse.ui.wizards.IWizardCategory";
	public static String I_WORKBENCH = "org.eclipse.ui.IWorkbench";
	public static String I_WORKBENCH_ACTION_CONSTANTS = "org.eclipse.ui.IWorkbenchActionConstants";
	public static String I_WORKBENCH_PAGE = "org.eclipse.ui.IWorkbenchPage";
	public static String I_WORKBENCH_PART = "org.eclipse.ui.IWorkbenchPart";
	public static String I_WORKBENCH_PART_REFERENCE = "org.eclipse.ui.IWorkbenchPartReference";
	public static String I_WORKBENCH_PREFERENCE_PAGE = "org.eclipse.ui.IWorkbenchPreferencePage";
	public static String I_WORKSPACE = IWorkspace.class.getName();
	public static String I_WORKSPACE_ROOT = IWorkspaceRoot.class.getName();
	public static String JFACE_DIALOG = "org.eclipse.jface.dialogs.Dialog";
	public static String JOB = org.eclipse.core.runtime.jobs.Job.class.getName();
	public static String J_FACE_RESOURCES = "org.eclipse.jface.resource.JFaceResources";
	public static String J_FACE_TOKEN = "org.eclipse.jface.text.rules.Token";
	public static String KEY_EVENT = "org.eclipse.swt.events.KeyEvent";
	public static String KEY_LISTENER = "org.eclipse.swt.events.KeyListener";
	public static String LABEL = "org.eclipse.swt.widgets.Label";
	public static String LABEL_PROVIDER = "org.eclipse.jface.viewers.LabelProvider";
	public static String LEXER = Lexer.class.getName();
	public static String LINK = "org.eclipse.swt.widgets.Link";
	public static String LINKED_HASH_MAP = LinkedHashMap.class.getName();
	public static String LINKED_HASH_SET = LinkedHashSet.class.getName();
	public static String LINKED_LIST = LinkedList.class.getName();
	public static String LIST = List.class.getName();
	public static String LISTENER = "org.eclipse.swt.widgets.Listener";
	public static String LISTENER_LIST = ListenerList.class.getName();
	public static String LIST_ITERATOR = ListIterator.class.getName();
	public static String LOCATION_LISTENER = "org.eclipse.swt.browser.LocationListener";
	public static String MANY_INVERSE = EObjectWithInverseResolvingEList.ManyInverse.class.getCanonicalName();
	public static String MAP = Map.class.getName();
	public static String MAP_ENTRY = Map.Entry.class.getCanonicalName();
	public static String MARKER_ANNOTATION = "org.eclipse.ui.texteditor.MarkerAnnotation";
	public static String MATCHER = Matcher.class.getName();
	public static String MENU = "org.eclipse.swt.widgets.Menu";
	public static String MENU_MANAGER = "org.eclipse.jface.action.MenuManager";
	public static String MESSAGE_BOX = "org.eclipse.swt.widgets.MessageBox";
	public static String MESSAGE_DIALOG = "org.eclipse.jface.dialogs.MessageDialog";
	public static String MESSAGE_DIGEST = MessageDigest.class.getName();
	public static String METHOD = java.lang.reflect.Method.class.getName();
	public static String MISMATCHED_NOT_SET_EXCEPTION = MismatchedNotSetException.class.getName();
	public static String MISMATCHED_RANGE_EXCEPTION = MismatchedRangeException.class.getName();
	public static String MISMATCHED_SET_EXCEPTION = MismatchedSetException.class.getName();
	public static String MISMATCHED_TOKEN_EXCEPTION = MismatchedTokenException.class.getName();
	public static String MISMATCHED_TREE_NODE_EXCEPTION = MismatchedTreeNodeException.class.getName();
	public static String MODEL_VALIDATION_SERVICE = ModelValidationService.class.getName();
	public static String MODIFY_EVENT = "org.eclipse.swt.events.ModifyEvent";
	public static String MODIFY_LISTENER = "org.eclipse.swt.events.ModifyListener";
	public static String MOUSE_EVENT = "org.eclipse.swt.events.MouseEvent";
	public static String MOUSE_LISTENER = "org.eclipse.swt.events.MouseListener";
	public static String NOTIFICATION = Notification.class.getName();
	public static String NOTIFICATION_CHAIN = NotificationChain.class.getName();
	public static String NOTIFIER = Notifier.class.getName();
	public static String NO_SUCH_ALGORITHM_EXCEPTION = NoSuchAlgorithmException.class.getName();
	public static String NO_VIABLE_ALT_EXCEPTION = NoViableAltException.class.getName();
	public static String NULL_POINTER_EXCEPTION = NullPointerException.class.getName();
	public static String OPEN_WINDOW_LISTENER = "org.eclipse.swt.browser.OpenWindowListener";
	public static String OUTPUT_STREAM = OutputStream.class.getName();
	public static String OUTPUT_STREAM_WRITER = OutputStreamWriter.class.getName();
	public static String PAGE = "org.eclipse.ui.part.Page";
	public static String PART_INIT_EXCEPTION = "org.eclipse.ui.PartInitException";
	public static String PATH = Path.class.getName();
	public static String PATTERN = java.util.regex.Pattern.class.getName();
	public static String PLATFORM = Platform.class.getName();
	public static String PLATFORM_UI = "org.eclipse.ui.PlatformUI";
	public static String POINT = "org.eclipse.swt.graphics.Point";
	public static String POSITION = "org.eclipse.jface.text.Position";
	public static String POSITION_BASED_TEXT_DIAGNOSTIC = "PositionBasedTextDiagnostic";
	public static String PREFERENCE_CONVERTER = "org.eclipse.jface.preference.PreferenceConverter";
	public static String PREFERENCE_PAGE = "org.eclipse.jface.preference.PreferencePage";
	public static String PRESENTATION_RECONCILER = "org.eclipse.jface.text.presentation.PresentationReconciler";
	public static String PRINTER_WRITER = PrintWriter.class.getName();
	public static String PROGRAM = "org.eclipse.swt.program.Program";
	public static String PROGRESS_ADAPTER = "org.eclipse.swt.browser.ProgressAdapter";
	public static String PROGRESS_EVENT = "org.eclipse.swt.browser.ProgressEvent";
	public static String PROJECTION_ANNOTATION = "org.eclipse.jface.text.source.projection.ProjectionAnnotation";
	public static String PROJECTION_ANNOTATION_MODEL = "org.eclipse.jface.text.source.projection.ProjectionAnnotationModel";
	public static String PROJECTION_SUPPORT = "org.eclipse.jface.text.source.projection.ProjectionSupport";
	public static String PROJECTION_VIEWER = "org.eclipse.jface.text.source.projection.ProjectionViewer";
	public static String PROPERTY_DESCRIPTOR = "org.eclipse.emf.edit.ui.provider.PropertyDescriptor";
	public static String PROPERTY_SHEET_PAGE = "org.eclipse.ui.views.properties.PropertySheetPage";
	public static String PROPERTY_SOURCE = "org.eclipse.emf.edit.ui.provider.PropertySource";
	public static String PROXY = Proxy.class.getName();
	public static String PUSHBACK_READER = PushbackReader.class.getName();
	public static String QUICK_ASSIST_ASSISTANT = "org.eclipse.jface.text.quickassist.QuickAssistAssistant";
	public static String READER = Reader.class.getName();
	public static String RECOGNITION_EXCEPTION = RecognitionException.class.getName();
	public static String RECOGNIZER_SHARED_STATE = org.antlr.runtime3_4_0.RecognizerSharedState.class.getName();
	public static String RECTANGLE = "org.eclipse.swt.graphics.Rectangle";
	public static String REFLECTIVE_ITEM_PROVIDER_ADAPTER_FACTORY = ReflectiveItemProviderAdapterFactory.class.getName();
	public static String REGION = "org.eclipse.jface.text.Region";
	public static String RESOLVER_SWITCH_FIELD_NAME = "resolverSwitch";
	public static String RESOURCE = org.eclipse.emf.ecore.resource.Resource.class.getName();
	public static String RESOURCES_PLUGIN = ResourcesPlugin.class.getName();
	public static String RESOURCE_BUNDLE = ResourceBundle.class.getName();
	public static String RESOURCE_DIAGNOSTIC = Diagnostic.class.getCanonicalName();
	public static String RESOURCE_FACTORY = Resource.Factory.class.getCanonicalName();
	public static String RESOURCE_IMPL = ResourceImpl.class.getName();
	public static String RESOURCE_ITEM_PROVIDER_ADAPTER_FACTORY = ResourceItemProviderAdapterFactory.class.getName();
	public static String RESOURCE_MARKER_ANNOTATION_MODEL = "org.eclipse.ui.texteditor.ResourceMarkerAnnotationModel";
	public static String RESOURCE_SET = ResourceSet.class.getName();
	public static String RESOURCE_SET_IMPL = ResourceSetImpl.class.getName();
	public static String RGB = "org.eclipse.swt.graphics.RGB";
	public static String SAFE_RUNNABLE = "org.eclipse.jface.util.SafeRunnable";
	public static String SAFE_RUNNER = SafeRunner.class.getName();
	public static String SCROLLABLE = "org.eclipse.swt.widgets.Scrollable";
	public static String SCROLL_BAR = "org.eclipse.swt.widgets.ScrollBar";
	public static String SELECTION_ADAPTER = "org.eclipse.swt.events.SelectionAdapter";
	public static String SELECTION_CHANGED_EVENT = "org.eclipse.jface.viewers.SelectionChangedEvent";
	public static String SELECTION_EVENT = "org.eclipse.swt.events.SelectionEvent";
	public static String SELECTION_LISTENER = "org.eclipse.swt.events.SelectionListener";
	public static String SELECT_MARKER_RULES_ACTION = "org.eclipse.ui.texteditor.SelectMarkerRulerAction";
	public static String SET = Set.class.getName();
	public static String SHELL = "org.eclipse.swt.widgets.Shell";
	public static String SLIDER = "org.eclipse.swt.widgets.Slider";
	public static String SOURCE_VIEWER_CONFIGURATION = "org.eclipse.jface.text.source.SourceViewerConfiguration";
	public static String STACK = Stack.class.getName();
	public static String STATUS = Status.class.getName();
	public static String STRING_BUILDER = StringBuilder.class.getName();
	public static String STRING_READER = StringReader.class.getName();
	public static String STRING_WRITER = StringWriter.class.getName();
	public static String STRUCTURED_SELECTION = "org.eclipse.jface.viewers.StructuredSelection";
	public static String STRUCTURED_VIEWER = "org.eclipse.jface.viewers.StructuredViewer";
	public static String STYLED_TEXT = "org.eclipse.swt.custom.StyledText";
	public static String STYLE_RANGE = "org.eclipse.swt.custom.StyleRange";
	public static String SWT = "org.eclipse.swt.SWT";
	public static String SWT_ERROR = "org.eclipse.swt.SWTError";
	public static String SWT_LIST = "org.eclipse.swt.widgets.List";
	public static String TEXT = "org.eclipse.swt.widgets.Text";
	public static String TEXT_ATTRIBUTE = "org.eclipse.jface.text.TextAttribute";
	public static String TEXT_EDITOR = "org.eclipse.ui.editors.text.TextEditor";
	public static String TEXT_INVOCATION_CONTEXT = "org.eclipse.jface.text.source.TextInvocationContext";
	public static String TEXT_LAYOUT = "org.eclipse.swt.graphics.TextLayout";
	public static String TEXT_PRESENTATION = "org.eclipse.jface.text.TextPresentation";
	public static String TEXT_SELECTION = "org.eclipse.jface.text.TextSelection";
	public static String TEXT_SOURCE_VIEWER_CONFIGURATION = "org.eclipse.ui.editors.text.TextSourceViewerConfiguration";
	public static String TEXT_STYLE = "org.eclipse.swt.graphics.TextStyle";
	public static String TEXT_VIEWER = "org.eclipse.jface.text.TextViewer";
	public static String TIMER = Timer.class.getName();
	public static String TIMER_TASK = TimerTask.class.getName();
	public static String TOOL_BAR_MANAGER = "org.eclipse.jface.action.ToolBarManager";
	public static String TREE_SELECTION = "org.eclipse.jface.viewers.TreeSelection";
	public static String TREE_VIEWER = "org.eclipse.jface.viewers.TreeViewer";
	public static String URI = org.eclipse.emf.common.util.URI.class.getName();
	public static String URI_CONVERTER = URIConverter.class.getName();
	public static String URL = URL.class.getName();
	public static String VERIFY_EVENT = "org.eclipse.swt.events.VerifyEvent";
	public static String VERIFY_KEY_LISTENER = "org.eclipse.swt.custom.VerifyKeyListener";
	public static String VERIFY_LISTENER = "org.eclipse.swt.events.VerifyListener"; 
	public static String VIEWER = "org.eclipse.jface.viewers.Viewer";
	public static String VIEWER_COMPARATOR = "org.eclipse.jface.viewers.ViewerComparator";
	public static String VIEWER_FILTER = "org.eclipse.jface.viewers.ViewerFilter";
	public static String WINDOW = "org.eclipse.jface.window.Window";
	public static String WINDOW_EVENT = "org.eclipse.swt.browser.WindowEvent";
	public static String WIZARD = "org.eclipse.jface.wizard.Wizard";
	public static String WIZARD_PAGE = "org.eclipse.jface.wizard.WizardPage";
	public static String WORKBENCH_CONTENT_PROVIDER = "org.eclipse.ui.model.WorkbenchContentProvider";
	public static String WORKBENCH_LABEL_PROVIDER = "org.eclipse.ui.model.WorkbenchLabelProvider";
	public static String XML_MEMENTO = "org.eclipse.ui.XMLMemento";
	
	public static String WIZARD_NEW_PROJECT_CREATION_PAGE = "org.eclipse.ui.dialogs.WizardNewProjectCreationPage";
	public static String WORKSPACE_MODIFY_OPERATION = "org.eclipse.ui.actions.WorkspaceModifyOperation";
	public static String SUB_PROGRESS_MONITOR = SubProgressMonitor.class.getName();
	public static String BASIC_NEW_PROJECT_RESOURCE_WIZARD = "org.eclipse.ui.wizards.newresource.BasicNewProjectResourceWizard";

	public static String ABSTRACT_DECORATED_TEXT_EDITOR_PREFERENCE_CONSTANTS = "org.eclipse.ui.texteditor.AbstractDecoratedTextEditorPreferenceConstants";
	
	public static String I_RECONCILER = "org.eclipse.jface.text.reconciler.IReconciler";
	public static String SPELLING_SERVICE = "org.eclipse.ui.texteditor.spelling.SpellingService";
	public static String I_RECONCILING_STRATEGY = "org.eclipse.jface.text.reconciler.IReconcilingStrategy";
	public static String SPELLING_RECONCILE_STRATEGY = "org.eclipse.ui.texteditor.spelling.SpellingReconcileStrategy";
	public static String I_SPELLING_PROBLEM_COLLECTOR = "org.eclipse.ui.texteditor.spelling.ISpellingProblemCollector";
	public static String SPELLING_PROBLEM = "org.eclipse.ui.texteditor.spelling.SpellingProblem";
	public static String MONO_RECONCILER = "org.eclipse.jface.text.reconciler.MonoReconciler";
}
